version: '3'

services:
  backend:
    build:
      dockerfile: docker/Dockerfile.local
      context: .
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    ports:
      - 6002:6002
    command: sh -c "npm run start:dev"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - ems-data:/var/lib/postgresql/data
      - ./init-unaccent.sql:/docker-entrypoint-initdb.d/init-unaccent.sql
    restart: unless-stopped

volumes:
  ems-data:
