name: CI/CD EMS External to VM

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: Build & Lint NestJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  deploy:
    name: Deploy to VM
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2223
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git reset --hard
            git pull origin develop
            docker-compose down --remove-orphans
            docker volume prune -f
            docker image prune -af
            docker-compose up -d --build
